name: Build Release
on:
  release:
    types:
      - published

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
        fetch-depth: 0

    - name: Get the Release Tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Update release file
      run: |
          # Overwrite the file 'release' with the tag name
          echo "${{ env.VERSION }}" | sed 's/^v//' > version

    - name: Commit and push updated version file
      # Adds a commit with the updated version file and pushes it to the master branch.
      # The version file is used by the auto-update script to determine the latest version of the plugin.
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add version
        git diff --cached --quiet || git commit -m "Update version to ${{ env.VERSION }}"
        git push origin HEAD:master

    - name: Zip Folder
      # Create a zip file of the repository, excluding unnecessary files and folders.
      # The zip file will be attached to the release.
      run: zip -r ${{ github.event.repository.name }}.zip . -x ".git/*" ".github/*" ".DS_Store" ".gitignore" ".python-version" ".editorconfig" ".isort.cfg" "requirements*.txt" "history/*" "tests/*"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ github.event.repository.name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: List files for debugging
      run: ls -R

    - name: VirusTotal Scan
      # Will run a VirustTotal scan and add the results to the release notes. Requires a VT API key in the repository secrets.
      uses: cssnr/virustotal-action@v1
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        file_globs: ${{ github.event.repository.name }}.zip
        release_heading: '### Virus Scan'
        update_release: true
