# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up Python 3.11
      uses: actions/setup-python@v5.4.0
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libjpeg-dev zlib1g-dev libpng-dev
        python -m pip install --upgrade pip
        pip install pytest pytest-xvfb
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    - name: Lint with flake8
      run: |
       pip install flake8

        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

        # Enable if you wish
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with xvfb-pytest
      run: |
        xvfb-run pytest -m "not slow"
